# Generated by Django 2.0.4 on 2018-05-01 14:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.api.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('things_i_love', models.TextField(blank=True, default='', null=True, verbose_name='things_i_love')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('joined_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='joined_date')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('registration_code', models.CharField(default=project.api.helpers.code_generator, max_length=15, unique=True, verbose_name='registration code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
